name: 'Request review'
description: 'A GitHub Action for requesting review'
branding:
  icon: 'user-check'
  color: 'green'
inputs:
  token:
    description: 'GitHub token'
    required: true
  pull-request-number:
    description: "Pull request's number"
    required: false
    default: github.actor
  reviewers:
    description: "Reviewers to add, in space separated list"
    required: false
    default: github.context.payload.pull_request.number
runs:
  using: 'node12'
  main: 'dist/index.js'
