name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'GitHub token'
    required: true
  pull-request-number:
    description: "Pull request's number"
    required: false
  reviewers:
    description: "Reviewers to add, in space separated list"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
